services:

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    restart: always
    network_mode: host
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://127.0.0.1:5432/keycloakdb
      KC_DB_USERNAME: keycloakdb
      KC_DB_PASSWORD: keycloakdb
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command:
      - start-dev
      - --http-enabled=true
      - --hostname=http://localhost:8080
      - --spi-theme--static-max-age=-1
      - --spi-theme--cache-themes=false
      - --spi-theme--cache-templates=false
